/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ImageRemoveRouteImport } from './routes/image.remove'
import { Route as ImageUploadRouteImport } from './routes/image.upload'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as AdminImageListPagenumRouteImport } from './routes/admin.image.list.$pagenum'
import { Route as AdminTraveloguePageListRouteImport } from './routes/admin.travelogue.page.list'
import { Route as AdminTraveloguePageEditPageidRouteImport } from './routes/admin.travelogue.page.edit.$pageid'
import { Route as AdminTraveloguePageEditPageidMainRouteImport } from './routes/admin.travelogue.page.edit.$pageid.main'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRemoveRoute = ImageRemoveRouteImport.update({
  id: '/image/remove',
  path: '/image/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageUploadRoute = ImageUploadRouteImport.update({
  id: '/image/upload',
  path: '/image/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImageListPagenumRoute = AdminImageListPagenumRouteImport.update({
  id: '/image/list/$pagenum',
  path: '/image/list/$pagenum',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTraveloguePageListRoute = AdminTraveloguePageListRouteImport.update({
  id: '/travelogue/page/list',
  path: '/travelogue/page/list',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTraveloguePageEditPageidRoute =
  AdminTraveloguePageEditPageidRouteImport.update({
    id: '/travelogue/page/edit/$pageid',
    path: '/travelogue/page/edit/$pageid',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTraveloguePageEditPageidMainRoute =
  AdminTraveloguePageEditPageidMainRouteImport.update({
    id: '/main',
    path: '/main',
    getParentRoute: () => AdminTraveloguePageEditPageidRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/image/remove': typeof ImageRemoveRoute
  '/image/upload': typeof ImageUploadRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/image/list/$pagenum': typeof AdminImageListPagenumRoute
  '/admin/travelogue/page/list': typeof AdminTraveloguePageListRoute
  '/admin/travelogue/page/edit/$pageid': typeof AdminTraveloguePageEditPageidRouteWithChildren
  '/admin/travelogue/page/edit/$pageid/main': typeof AdminTraveloguePageEditPageidMainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/image/remove': typeof ImageRemoveRoute
  '/image/upload': typeof ImageUploadRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/image/list/$pagenum': typeof AdminImageListPagenumRoute
  '/admin/travelogue/page/list': typeof AdminTraveloguePageListRoute
  '/admin/travelogue/page/edit/$pageid': typeof AdminTraveloguePageEditPageidRouteWithChildren
  '/admin/travelogue/page/edit/$pageid/main': typeof AdminTraveloguePageEditPageidMainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/image/remove': typeof ImageRemoveRoute
  '/image/upload': typeof ImageUploadRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/image/list/$pagenum': typeof AdminImageListPagenumRoute
  '/admin/travelogue/page/list': typeof AdminTraveloguePageListRoute
  '/admin/travelogue/page/edit/$pageid': typeof AdminTraveloguePageEditPageidRouteWithChildren
  '/admin/travelogue/page/edit/$pageid/main': typeof AdminTraveloguePageEditPageidMainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/$'
    | '/image/remove'
    | '/image/upload'
    | '/api/rpc/$'
    | '/admin/image/list/$pagenum'
    | '/admin/travelogue/page/list'
    | '/admin/travelogue/page/edit/$pageid'
    | '/admin/travelogue/page/edit/$pageid/main'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/$'
    | '/image/remove'
    | '/image/upload'
    | '/api/rpc/$'
    | '/admin/image/list/$pagenum'
    | '/admin/travelogue/page/list'
    | '/admin/travelogue/page/edit/$pageid'
    | '/admin/travelogue/page/edit/$pageid/main'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/$'
    | '/image/remove'
    | '/image/upload'
    | '/api/rpc/$'
    | '/admin/image/list/$pagenum'
    | '/admin/travelogue/page/list'
    | '/admin/travelogue/page/edit/$pageid'
    | '/admin/travelogue/page/edit/$pageid/main'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ImageRemoveRoute: typeof ImageRemoveRoute
  ImageUploadRoute: typeof ImageUploadRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/remove': {
      id: '/image/remove'
      path: '/image/remove'
      fullPath: '/image/remove'
      preLoaderRoute: typeof ImageRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/upload': {
      id: '/image/upload'
      path: '/image/upload'
      fullPath: '/image/upload'
      preLoaderRoute: typeof ImageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/image/list/$pagenum': {
      id: '/admin/image/list/$pagenum'
      path: '/image/list/$pagenum'
      fullPath: '/admin/image/list/$pagenum'
      preLoaderRoute: typeof AdminImageListPagenumRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/travelogue/page/list': {
      id: '/admin/travelogue/page/list'
      path: '/travelogue/page/list'
      fullPath: '/admin/travelogue/page/list'
      preLoaderRoute: typeof AdminTraveloguePageListRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/travelogue/page/edit/$pageid': {
      id: '/admin/travelogue/page/edit/$pageid'
      path: '/travelogue/page/edit/$pageid'
      fullPath: '/admin/travelogue/page/edit/$pageid'
      preLoaderRoute: typeof AdminTraveloguePageEditPageidRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/travelogue/page/edit/$pageid/main': {
      id: '/admin/travelogue/page/edit/$pageid/main'
      path: '/main'
      fullPath: '/admin/travelogue/page/edit/$pageid/main'
      preLoaderRoute: typeof AdminTraveloguePageEditPageidMainRouteImport
      parentRoute: typeof AdminTraveloguePageEditPageidRoute
    }
  }
}

interface AdminTraveloguePageEditPageidRouteChildren {
  AdminTraveloguePageEditPageidMainRoute: typeof AdminTraveloguePageEditPageidMainRoute
}

const AdminTraveloguePageEditPageidRouteChildren: AdminTraveloguePageEditPageidRouteChildren =
  {
    AdminTraveloguePageEditPageidMainRoute:
      AdminTraveloguePageEditPageidMainRoute,
  }

const AdminTraveloguePageEditPageidRouteWithChildren =
  AdminTraveloguePageEditPageidRoute._addFileChildren(
    AdminTraveloguePageEditPageidRouteChildren,
  )

interface AdminRouteChildren {
  AdminImageListPagenumRoute: typeof AdminImageListPagenumRoute
  AdminTraveloguePageListRoute: typeof AdminTraveloguePageListRoute
  AdminTraveloguePageEditPageidRoute: typeof AdminTraveloguePageEditPageidRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImageListPagenumRoute: AdminImageListPagenumRoute,
  AdminTraveloguePageListRoute: AdminTraveloguePageListRoute,
  AdminTraveloguePageEditPageidRoute:
    AdminTraveloguePageEditPageidRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ImageRemoveRoute: ImageRemoveRoute,
  ImageUploadRoute: ImageUploadRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
