/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ImageRemoveRouteImport } from './routes/image.remove'
import { Route as ImageUploadRouteImport } from './routes/image.upload'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as TlgPageIdRouteImport } from './routes/tlg.page.$id'
import { Route as AdminImageListPagenumRouteImport } from './routes/admin.image.list.$pagenum'
import { Route as AdminTlgPageListRouteImport } from './routes/admin.tlg.page.list'
import { Route as AdminTlgPageEditIdRouteImport } from './routes/admin.tlg.page.edit.$id'
import { Route as AdminTlgPageEditIdMainRouteImport } from './routes/admin.tlg.page.edit.$id.main'
import { Route as AdminTlgPageEditIdSalerRouteImport } from './routes/admin.tlg.page.edit.$id.saler'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRemoveRoute = ImageRemoveRouteImport.update({
  id: '/image/remove',
  path: '/image/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageUploadRoute = ImageUploadRouteImport.update({
  id: '/image/upload',
  path: '/image/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TlgPageIdRoute = TlgPageIdRouteImport.update({
  id: '/tlg/page/$id',
  path: '/tlg/page/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImageListPagenumRoute = AdminImageListPagenumRouteImport.update({
  id: '/image/list/$pagenum',
  path: '/image/list/$pagenum',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTlgPageListRoute = AdminTlgPageListRouteImport.update({
  id: '/tlg/page/list',
  path: '/tlg/page/list',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTlgPageEditIdRoute = AdminTlgPageEditIdRouteImport.update({
  id: '/tlg/page/edit/$id',
  path: '/tlg/page/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTlgPageEditIdMainRoute = AdminTlgPageEditIdMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => AdminTlgPageEditIdRoute,
} as any)
const AdminTlgPageEditIdSalerRoute = AdminTlgPageEditIdSalerRouteImport.update({
  id: '/saler',
  path: '/saler',
  getParentRoute: () => AdminTlgPageEditIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/image/remove': typeof ImageRemoveRoute
  '/image/upload': typeof ImageUploadRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/tlg/page/$id': typeof TlgPageIdRoute
  '/admin/image/list/$pagenum': typeof AdminImageListPagenumRoute
  '/admin/tlg/page/list': typeof AdminTlgPageListRoute
  '/admin/tlg/page/edit/$id': typeof AdminTlgPageEditIdRouteWithChildren
  '/admin/tlg/page/edit/$id/main': typeof AdminTlgPageEditIdMainRoute
  '/admin/tlg/page/edit/$id/saler': typeof AdminTlgPageEditIdSalerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/image/remove': typeof ImageRemoveRoute
  '/image/upload': typeof ImageUploadRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/tlg/page/$id': typeof TlgPageIdRoute
  '/admin/image/list/$pagenum': typeof AdminImageListPagenumRoute
  '/admin/tlg/page/list': typeof AdminTlgPageListRoute
  '/admin/tlg/page/edit/$id': typeof AdminTlgPageEditIdRouteWithChildren
  '/admin/tlg/page/edit/$id/main': typeof AdminTlgPageEditIdMainRoute
  '/admin/tlg/page/edit/$id/saler': typeof AdminTlgPageEditIdSalerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/image/remove': typeof ImageRemoveRoute
  '/image/upload': typeof ImageUploadRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/tlg/page/$id': typeof TlgPageIdRoute
  '/admin/image/list/$pagenum': typeof AdminImageListPagenumRoute
  '/admin/tlg/page/list': typeof AdminTlgPageListRoute
  '/admin/tlg/page/edit/$id': typeof AdminTlgPageEditIdRouteWithChildren
  '/admin/tlg/page/edit/$id/main': typeof AdminTlgPageEditIdMainRoute
  '/admin/tlg/page/edit/$id/saler': typeof AdminTlgPageEditIdSalerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/$'
    | '/image/remove'
    | '/image/upload'
    | '/api/rpc/$'
    | '/tlg/page/$id'
    | '/admin/image/list/$pagenum'
    | '/admin/tlg/page/list'
    | '/admin/tlg/page/edit/$id'
    | '/admin/tlg/page/edit/$id/main'
    | '/admin/tlg/page/edit/$id/saler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/$'
    | '/image/remove'
    | '/image/upload'
    | '/api/rpc/$'
    | '/tlg/page/$id'
    | '/admin/image/list/$pagenum'
    | '/admin/tlg/page/list'
    | '/admin/tlg/page/edit/$id'
    | '/admin/tlg/page/edit/$id/main'
    | '/admin/tlg/page/edit/$id/saler'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/$'
    | '/image/remove'
    | '/image/upload'
    | '/api/rpc/$'
    | '/tlg/page/$id'
    | '/admin/image/list/$pagenum'
    | '/admin/tlg/page/list'
    | '/admin/tlg/page/edit/$id'
    | '/admin/tlg/page/edit/$id/main'
    | '/admin/tlg/page/edit/$id/saler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ImageRemoveRoute: typeof ImageRemoveRoute
  ImageUploadRoute: typeof ImageUploadRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  TlgPageIdRoute: typeof TlgPageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/remove': {
      id: '/image/remove'
      path: '/image/remove'
      fullPath: '/image/remove'
      preLoaderRoute: typeof ImageRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image/upload': {
      id: '/image/upload'
      path: '/image/upload'
      fullPath: '/image/upload'
      preLoaderRoute: typeof ImageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tlg/page/$id': {
      id: '/tlg/page/$id'
      path: '/tlg/page/$id'
      fullPath: '/tlg/page/$id'
      preLoaderRoute: typeof TlgPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/image/list/$pagenum': {
      id: '/admin/image/list/$pagenum'
      path: '/image/list/$pagenum'
      fullPath: '/admin/image/list/$pagenum'
      preLoaderRoute: typeof AdminImageListPagenumRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tlg/page/list': {
      id: '/admin/tlg/page/list'
      path: '/tlg/page/list'
      fullPath: '/admin/tlg/page/list'
      preLoaderRoute: typeof AdminTlgPageListRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tlg/page/edit/$id': {
      id: '/admin/tlg/page/edit/$id'
      path: '/tlg/page/edit/$id'
      fullPath: '/admin/tlg/page/edit/$id'
      preLoaderRoute: typeof AdminTlgPageEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tlg/page/edit/$id/main': {
      id: '/admin/tlg/page/edit/$id/main'
      path: '/main'
      fullPath: '/admin/tlg/page/edit/$id/main'
      preLoaderRoute: typeof AdminTlgPageEditIdMainRouteImport
      parentRoute: typeof AdminTlgPageEditIdRoute
    }
    '/admin/tlg/page/edit/$id/saler': {
      id: '/admin/tlg/page/edit/$id/saler'
      path: '/saler'
      fullPath: '/admin/tlg/page/edit/$id/saler'
      preLoaderRoute: typeof AdminTlgPageEditIdSalerRouteImport
      parentRoute: typeof AdminTlgPageEditIdRoute
    }
  }
}

interface AdminTlgPageEditIdRouteChildren {
  AdminTlgPageEditIdMainRoute: typeof AdminTlgPageEditIdMainRoute
  AdminTlgPageEditIdSalerRoute: typeof AdminTlgPageEditIdSalerRoute
}

const AdminTlgPageEditIdRouteChildren: AdminTlgPageEditIdRouteChildren = {
  AdminTlgPageEditIdMainRoute: AdminTlgPageEditIdMainRoute,
  AdminTlgPageEditIdSalerRoute: AdminTlgPageEditIdSalerRoute,
}

const AdminTlgPageEditIdRouteWithChildren =
  AdminTlgPageEditIdRoute._addFileChildren(AdminTlgPageEditIdRouteChildren)

interface AdminRouteChildren {
  AdminImageListPagenumRoute: typeof AdminImageListPagenumRoute
  AdminTlgPageListRoute: typeof AdminTlgPageListRoute
  AdminTlgPageEditIdRoute: typeof AdminTlgPageEditIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImageListPagenumRoute: AdminImageListPagenumRoute,
  AdminTlgPageListRoute: AdminTlgPageListRoute,
  AdminTlgPageEditIdRoute: AdminTlgPageEditIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ImageRemoveRoute: ImageRemoveRoute,
  ImageUploadRoute: ImageUploadRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  TlgPageIdRoute: TlgPageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
